// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajqnkddszqtfbjnyamuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqcW5rZGRzenF0ZmJqbnlhbXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjE4NTQsImV4cCI6MjA2OTIzNzg1NH0.XbvHSXJ5UYBuMGFx02tALA3pUhs_bEHSW2UPfJX79e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});